[tools]
sops = "3.13.3"
uv = "0.8.12"

[env]
_.file = { path = ".env.json", redact = true }

# see https://openrouter.ai/openai/gpt-5-nano
MODEL = "openai/gpt-5-nano"
# see https://openrouter.ai/openai/text-embedding-3-small
EMBEDDING_MODEL = "openai/text-embedding-3-small"
